# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EjongHyuck
title-bold: EjongHyuck
title-normal: Game Developer
email: ejonghyuck@live.co.kr
description: Junior Game Programmer at ArasoPandan. <br />I love C#, Javascript and 3D Graphics rendering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ejonghyuck.github.io" # the base hostname & protocol for your site
author: 
street_address: 9-7, Yeonhui-ro 35-gil
city: Seoul
state: 
zip_code: KS013
country: Republic Of Korea
phone: +82) 10-9403-5906

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
#  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: 
facebook_url: https://www.facebook.com/jonghyuck.lee.9
github_url: https://github.com/ejonghyuck
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/HansMakart

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: HansMakart
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
